const ACHIEVEMENTS = [
  { code: 'first_steps', name: 'First Steps', description: 'Review your first card', icon: '🌱', check: s => s.total_reviews >= 1 },
  { code: 'streak_3', name: 'Getting Started', description: 'Reach a 3-day streak', icon: '🔥', check: s => s.longest_streak >= 3 },
  { code: 'streak_7', name: 'Week Warrior', description: 'Reach a 7-day streak', icon: '🔥', check: s => s.longest_streak >= 7 },
  { code: 'streak_14', name: 'Fortnight Fighter', description: 'Reach a 14-day streak', icon: '🔥', check: s => s.longest_streak >= 14 },
  { code: 'streak_30', name: 'Monthly Master', description: 'Reach a 30-day streak', icon: '🔥', check: s => s.longest_streak >= 30 },
  { code: 'streak_50', name: 'Halfway to a Hundred', description: 'Reach a 50-day streak', icon: '🔥', check: s => s.longest_streak >= 50 },
  { code: 'streak_100', name: 'Unstoppable', description: 'Reach a 100-day streak', icon: '🐉', check: s => s.longest_streak >= 100 },
  { code: 'streak_200', name: 'Iron Will', description: 'Reach a 200-day streak', icon: '🛡️', check: s => s.longest_streak >= 200 },
  { code: 'streak_365', name: 'Year of the Dragon', description: 'Reach a 365-day streak', icon: '🐲', check: s => s.longest_streak >= 365 },
  { code: 'words_10', name: 'Vocabulary Builder', description: 'Learn 10 words', icon: '📚', check: s => s.learned_cards >= 10 },
  { code: 'words_50', name: 'Word Collector', description: 'Learn 50 words', icon: '📚', check: s => s.learned_cards >= 50 },
  { code: 'words_100', name: 'Centurion', description: 'Learn 100 words', icon: '📗', check: s => s.learned_cards >= 100 },
  { code: 'words_200', name: 'Word Hoarder', description: 'Learn 200 words', icon: '📖', check: s => s.learned_cards >= 200 },
  { code: 'words_350', name: 'Fluent-ish', description: 'Learn 350 words', icon: '🗣️', check: s => s.learned_cards >= 350 },
  { code: 'words_500', name: 'Lexicon Legend', description: 'Learn 500 words', icon: '🏆', check: s => s.learned_cards >= 500 },
  { code: 'words_750', name: 'Word Wizard', description: 'Learn 750 words', icon: '🧙', check: s => s.learned_cards >= 750 },
  { code: 'words_1000', name: 'Master of Words', description: 'Learn 1,000 words', icon: '💎', check: s => s.learned_cards >= 1000 },
  { code: 'words_1500', name: 'Walking Dictionary', description: 'Learn 1,500 words', icon: '📕', check: s => s.learned_cards >= 1500 },
  { code: 'reviews_100', name: 'Dedicated Learner', description: 'Complete 100 reviews', icon: '✅', check: s => s.total_reviews >= 100 },
  { code: 'reviews_500', name: 'Persistent Practicer', description: 'Complete 500 reviews', icon: '✅', check: s => s.total_reviews >= 500 },
  { code: 'reviews_1000', name: 'Review Machine', description: 'Complete 1,000 reviews', icon: '⚙️', check: s => s.total_reviews >= 1000 },
  { code: 'reviews_2500', name: 'Grindset', description: 'Complete 2,500 reviews', icon: '⚙️', check: s => s.total_reviews >= 2500 },
  { code: 'reviews_5000', name: 'Review Veteran', description: 'Complete 5,000 reviews', icon: '🥇', check: s => s.total_reviews >= 5000 },
  { code: 'reviews_10000', name: 'Review Legend', description: 'Complete 10,000 reviews', icon: '🏅', check: s => s.total_reviews >= 10000 },
  { code: 'reviews_25000', name: 'Eternal Student', description: 'Complete 25,000 reviews', icon: '🌟', check: s => s.total_reviews >= 25000 },
  { code: 'deck_complete', name: 'Topic Champion', description: 'Complete your first topic', icon: '🎯', check: s => s.completed_decks >= 1 },
  { code: 'decks_5', name: 'Explorer', description: 'Complete 5 topics', icon: '🗺️', check: s => s.completed_decks >= 5 },
  { code: 'decks_10', name: 'Cartographer', description: 'Complete 10 topics', icon: '🧭', check: s => s.completed_decks >= 10 },
  { code: 'decks_20', name: 'Trailblazer', description: 'Complete 20 topics', icon: '🏔️', check: s => s.completed_decks >= 20 },
  { code: 'decks_35', name: 'Pathfinder', description: 'Complete 35 topics', icon: '🧗', check: s => s.completed_decks >= 35 },
  { code: 'decks_50', name: 'Conqueror', description: 'Complete 50 topics', icon: '⚔️', check: s => s.completed_decks >= 50 },
  { code: 'decks_75', name: 'Grand Tour', description: 'Complete 75 topics', icon: '🚩', check: s => s.completed_decks >= 75 },
  { code: 'decks_all', name: 'Welsh Master', description: 'Complete every topic', icon: '👑', check: s => s.total_decks > 0 && s.completed_decks >= s.total_decks },
];

module.exports = { ACHIEVEMENTS };
